DROP TABLE users;
DROP TABLE chats;
CREATE TABLE users(id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(50), email VARCHAR(50), password VARCHAR(100));
CREATE TABLE chats(id INT PRIMARY KEY AUTO_INCREMENT, json_users TEXT, json_messages MEDIUMTEXT);
